// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://xmls.skatteverket.se/se/skatteverket/ht/komponent/begaran/6.0
package rotrut

import (
	"encoding/xml"
)

// XSD ComplexType declarations

type ArendeUtfortArbeteRotTYPE struct {
	XMLName xml.Name

	Bygg *TimmarMaterialTYPE `xml:"Bygg"`

	El *TimmarMaterialTYPE `xml:"El"`

	GlasPlatarbete *TimmarMaterialTYPE `xml:"GlasPlatarbete"`

	MarkDraneringarbete *TimmarMaterialTYPE `xml:"MarkDraneringarbete"`

	Murning *TimmarMaterialTYPE `xml:"Murning"`

	MalningTapetsering *TimmarMaterialTYPE `xml:"MalningTapetsering"`

	Vvs *TimmarMaterialTYPE `xml:"Vvs"`

	InnerXml string `xml:",innerxml"`
}

type ArendeUtfortArbeteRutTYPE struct {
	XMLName xml.Name

	Stadning *TimmarMaterialTYPE `xml:"Stadning"`

	KladOchTextilvard *TimmarMaterialTYPE `xml:"KladOchTextilvard"`

	Snoskottning *TimmarMaterialTYPE `xml:"Snoskottning"`

	Tradgardsarbete *TimmarMaterialTYPE `xml:"Tradgardsarbete"`

	Barnpassning *TimmarMaterialTYPE `xml:"Barnpassning"`

	Personligomsorg *TimmarMaterialTYPE `xml:"Personligomsorg"`

	Flyttjanster *TimmarMaterialTYPE `xml:"Flyttjanster"`

	ItTjanster *TimmarMaterialTYPE `xml:"ItTjanster"`

	ReparationAvVitvaror *TimmarMaterialTYPE `xml:"ReparationAvVitvaror"`

	Moblering *TimmarMaterialTYPE `xml:"Moblering"`

	TillsynAvBostad *TimmarMaterialTYPE `xml:"TillsynAvBostad"`

	TransportTillForsaljning *SchablonarbeteTYPE `xml:"TransportTillForsaljning"`

	TvattVidTvattinrattning *SchablonarbeteTYPE `xml:"TvattVidTvattinrattning"`

	InnerXml string `xml:",innerxml"`
}

type ArendeTYPE struct {
	XMLName xml.Name

	Kopare PeOrgNrTYPE `xml:"Kopare"`

	BetalningsDatum DatumTYPE `xml:"BetalningsDatum"`

	PrisForArbete string `xml:"PrisForArbete"`

	BetaltBelopp BeloppTYPE `xml:"BetaltBelopp"`

	BegartBelopp BeloppTYPE `xml:"BegartBelopp"`

	FakturaNr *FakturaNrTYPE `xml:"FakturaNr"`

	Ovrigkostnad *OvrigKostnadTYPE `xml:"Ovrigkostnad"`

	InnerXml string `xml:",innerxml"`
}

type RotArendeTYPE struct {
	XMLName xml.Name

	Fastighetsbeteckning *FastighetsbeteckningTYPE `xml:"Fastighetsbeteckning"`

	LagenhetsNr *LagenhetsNrTYPE `xml:"LagenhetsNr"`

	BrfOrgNr *BrfOrgNrTYPE `xml:"BrfOrgNr"`

	UtfortArbete *ArendeUtfortArbeteRotTYPE `xml:"UtfortArbete"`

	Kopare PeOrgNrTYPE `xml:"Kopare"`

	BetalningsDatum DatumTYPE `xml:"BetalningsDatum"`

	PrisForArbete string `xml:"PrisForArbete"`

	BetaltBelopp BeloppTYPE `xml:"BetaltBelopp"`

	BegartBelopp BeloppTYPE `xml:"BegartBelopp"`

	FakturaNr *FakturaNrTYPE `xml:"FakturaNr"`

	Ovrigkostnad *OvrigKostnadTYPE `xml:"Ovrigkostnad"`

	InnerXml string `xml:",innerxml"`
}

type HushallArendeTYPE struct {
	XMLName xml.Name

	UtfortArbete *ArendeUtfortArbeteRutTYPE `xml:"UtfortArbete"`

	Kopare PeOrgNrTYPE `xml:"Kopare"`

	BetalningsDatum DatumTYPE `xml:"BetalningsDatum"`

	PrisForArbete string `xml:"PrisForArbete"`

	BetaltBelopp BeloppTYPE `xml:"BetaltBelopp"`

	BegartBelopp BeloppTYPE `xml:"BegartBelopp"`

	FakturaNr FakturaNrTYPE `xml:"FakturaNr"`

	Ovrigkostnad OvrigKostnadTYPE `xml:"Ovrigkostnad"`

	InnerXml string `xml:",innerxml"`
}

type HushallBegaranTYPE struct {
	XMLName xml.Name

	Arenden []HushallArendeTYPE `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

type RotBegaranTYPE struct {
	XMLName xml.Name

	Arenden []RotArendeTYPE `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

type TimmarMaterialTYPE struct {
	XMLName xml.Name

	AntalTimmar AntalTimmarTYPE `xml:"AntalTimmar"`

	Materialkostnad MaterialkostnadTYPE `xml:"Materialkostnad"`

	InnerXml string `xml:",innerxml"`
}

type SchablonarbeteTYPE struct {
	XMLName xml.Name

	Utfort bool `xml:",any"`

	InnerXml string `xml:",innerxml"`
}

// XSD SimpleType declarations

type NamnPaBegaranTYPE string

type FakturaNrTYPE string

type BrfOrgNrTYPE string

type LagenhetsNrTYPE string

type FastighetsbeteckningTYPE string

type MaterialkostnadTYPE int64

type AntalTimmarTYPE int64

type OvrigKostnadTYPE int64

type BeloppTYPE int64

type DatumTYPE string

type PeOrgNrTYPE string
