// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://xmls.skatteverket.se/se/skatteverket/ht/begaran/6.0
package rotrut

import (
	"encoding/xml"
)

// Element
type Begaran struct {
	XMLName xml.Name `xml:"Begaran"`

	NamnPaBegaran NamnPaBegaranTYPE `xml:"NamnPaBegaran"`

	RotBegaran *RotBegaranTYPE `xml:"RotBegaran"`

	HushallBegaran *HushallBegaranTYPE `xml:"HushallBegaran"`
}

// XSD ComplexType declarations

// XSD SimpleType declarations
